package com.example.application;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Set;

public class ProductTypes {

	public static final Set<String> VALUES = Set.of("Pumpice za izmlazanje", "DVD/blu-rej plejeri",
			"Regeneratori za kućne ljubimce", "Berberske makaze", "Farbe za kosu", "Antifrizi i rashladne tečnosti",
			"Igračke za motorne veštine", "Ćebad za bebe", "Zidno osvetljenje", "Laserski pokazivači",
			"Jastuci za krevet", "Jorganske navlake", "Šatori za kampovanje", "Lopte za vežbanje", "Diktafoni",
			"Sigurnosne brave za decu", "Ramovi za slike", "Dnevne i noćne kreme", "Višenamenska električna kuvala",
			"Sprejevi za fiksiranje šminke", "Maske za lice", "Gelovi za lice", "Sportski steznici",
			"Ženski donji veš za jednokratnu upotrebu", "Hranljive kreme za telo", "Čaršavi za dečje krevece",
			"Stoni noževi", "Filteri za vodu", "Sprejevi za zaštitu od sunca", "Kozmetički koferi",
			"Stolice za bebe/malu decu", "Zavese za tuševe", "Vreće za čuvanje hrane", "Kreme za stopala",
			"Kuke za tuš-zavese", "Aparati za kuvanje pirinča", "Lepak za nokte", "Dodaci za kolica za drugo dete",
			"Jastuci za bebe", "Pametni telefoni", "Obuća za vodu", "BallPointPens", "Podni jastuci i otomani",
			"Prenosni klima uređaji", "Kompleti sa vodenim bojicama za decu", "Dečje igračke - figurice",
			"Čeone i ravne brusilice", "Čaršavi za krevet", "Jastučići od vate", "Korpe za hleb",
			"Kuhinjski dozatori i zidni držači", "Uvijači za trepavice", "Stepenici za decu",
			"Sprejevi za samopotamnjivanje", "Posude za sir", "CommercialRefrigeratorsFreezers", "Dozeri za sapun",
			"Konci i trake za zube", "Sportski satovi", "Čaše za šampanjac", "Trimeri za bradu",
			"Sprejevi za zaštitu kose od toplote", "Pribor za pravljenje markera", "Vesla",
			"Završni slojevi za fiksiranje laka za nokte", "Pene za brijanje", "Čaše za pivo",
			"Igre, igračke i nalepnice za kupanje", "Modne patike", "Losioni posle brijanja",
			"Električni lonci za lagano kuvanje", "Dečje igračke za svetleće crtanje", "Kolutovi za salvete",
			"Povezi za ruke", "Električni trotineti", "Spavaćice", "Portikle za bebe", "Igre sa kartama",
			"Baštenski usisivači", "Čišćenje vozila i pribor", "Delovi kutija za skladištenje", "Ploče šporeta",
			"Dečja oprema za šivenje", "Masažeri za negu kože", "Kreme za brijanje",
			"Električne cediljke za citrusno voće", "Sportske kape", "Sjajevi za usne", "Korektori", "Toaletne vode",
			"Ručni satovi", "Proizvodi za žensku higijenu", "Aparati za pravljenje palačinki", "Modne naočare",
			"Štitnici od sunca za kolica za bebe", "Torbe za prenosne računare", "Oprema za ljuljaške za igrališta",
			"Trotineti", "Merdevine", "Slagalice", "Dečji naučni setovi i igračke", "Tečnosti za ispiranje usta",
			"Sportski džemperi i duksevi sa kapuljačom", "Ljuljaške za bebe", "Aparati za negu kože",
			"Zdele za mešanje", "Muzičke igračke", "Kompleti peškira", "Dodatna oprema za zavese za kadu",
			"Držači za kravate", "Dekorativno osvetljenje", "Kompasi za navigaciju", "Lonci za supu",
			"Dečji radni stolovi", "Maske za ruke", "Torbe i mreže za kolica za bebe", "Kosilice za travu", "Zvečke",
			"Viseći skladišni organizeri", "Rezervni delovi i oprema za mašine za sušenje veša",
			"Video monitori za bebe", "Trambuline za vežbanje", "Kreme za depilaciju",
			"Tonici za pranje i čišćenje lica", "Aparati za smuti", "Osveživači daha", "Ruževi", "Pojas za mršavljenje",
			"Vakuum gume za otpušavanje", "Tečnosti za sušenje laka za nokte", "Dečja oprema za plivanje",
			"Humidifiers", "Roštilji i ploče za pečenje napolju", "Šipke i držači za peškire", "Pancerice", "Papuče",
			"Sačevi", "Oružje-igračke", "Kuke za kućno skladištenje", "Proteinski suplementi", "Filteri za vazduh",
			"Nega za depilaciju", "Kompleti dečje opreme za plivanje", "Fluorescentne sijalice",
			"Kuhinjske posude za skladištenje", "Rukavice za farbanje kose", "Televizori",
			"Međuzubne (interdentalne) četkice", "Krpe za čišćenje", "Šminka za konturisanje", "Guralice", "Zamrzivači",
			"Sredstva za skidanje kamenca", "Prekrivači za unutrašnjost vozila i pribor", "Zvučnici za automobile",
			"Stone lampe", "Ogradice za decu", "Šerpe", "Tanjiri za ručavanje", "Torbe za čuvanje povrća",
			"Podloge za spavanje", "Bebi mreže protiv komaraca", "Nakit i pirsing za telo", "Držači kapsula kafe",
			"Prenosive kružne testere", "Kompleti nameštaja za spavaće sobe",
			"Proizvodi za negu kože i šapa za kućne ljubimce", "Prekrivači", "Mobilni telefoni",
			"Staze za vozila-igračke", "Oprema za automobiliće i auto staze", "Ajlajneri", "Kompleti za negu kože tela",
			"Losioni za zaštitu od sunca", "Cipele", "Baterijske lampe",
			"Rezervni delovi i oprema za mašine za pranje veša", "Prostirke za vežbanje",
			"Korektori za područje oko očiju", "Radio-aparati", "Putne torbe za dečja kolica", "Jorgani",
			"Tobogani za decu", "Sapuni", "Električni uređaji za spiralno rezanje", "Vlažna hrana za pse",
			"Kontaktna sočiva", "Trpezarijske stolice", "Voskovi za kosu",
			"Kolonjske vode i dezodoransi za kućne ljubimce", "Inženjerski setovi za decu", "Senke za oči",
			"Dečji setovi za pravljenje parfema", "Tosteri", "Usisivači za pepeo", "Ulja za brijanje",
			"Prajmeri za trepavice", "Nega vozila i pribor", "Električne grejalice", "Kompresori za vazduh",
			"Prajmeri za šminku", "Čaše za koktele i likere", "Plafonsko osvetljenje", "Četkice za usne",
			"Češljevi i četke za bradu", "Posude za čuvanje hrane", "Spoljno osvetljenje", "Četke za šminku",
			"Čaše za vodu", "Centralne kontrolne jedinice za pametne domove", "Štitnici/odbojnici za krevece",
			"Delovi za setove igračaka", "Olovke za obrve", "Kozmetičke pincete", "Aktovke",
			"Dvokrilni frižideri-zamrzivači", "Zastori za krevece", "Cucle/varalice za bebe", "Držači za salvete",
			"Dečje fotelje", "Aparati za vakuumsko zatvaranje kesa", "Uređaji za čišćenje visokim pritiskom",
			"Brijači za žene", "Aparati za pravljenje kolačića i krofnica", "Stočići za hodnik", "Stalci za odeću",
			"Balzami za negu kože posle brijanja", "Dečji kalupi za modeliranje", "Posude/šolje",
			"Pribor za jelo i kompleti noževa", "Cucle za flašice", "Piling za telo", "Ftines vreća sa opterećenjem",
			"Makaze za orezivanje", "Klupe i postolja za trening", "Dušeci", "Električni gril",
			"Pene za pranje i čišćenje lica", "Perike", "Baze za lak za nokte", "Sportski kaiševi", "Friteze",
			"Delovi i dodatna oprema za šivaće mašine", "Hranilice i dozatori za vodu za pernate ljubimce",
			"Aparati za vafle", "Blenderi", "Dečje magnetne table za crtanje", "Balzami za nokte", "Električne rende",
			"Posude za pečenje", "Platforme za step aerobik", "Bebi žvakalice", "Kreme za tuširanje", "Kuhinjske krpe",
			"Narukvice", "Materijali za dečje komplete za umetnost i rukotvorine", "Šminka za decu",
			"Sredstva za oblikovanje kose", "Kućice za igru", "Podloge za opremu za vežbanje",
			"Poslastice za ptice ljubimce", "Minđuše", "Haljine", "Gelovi za negu kože posle brijanja",
			"Automobilski krovovi i krovni prtljažnici", "Čašice za kafu", "Muški brijači",
			"Dodaci za miksere/multipraktike", "Štitnici za odbojku", "Ručni usisivači", "Aparati za peglanje na paru",
			"Gume za bicikl", "Šamponi za kućne ljubimce", "Automobilska sedišta za bebe", "Sudopere",
			"Baze za senku za oči", "Kompleti pozorišne šminke za decu", "Kuhinjski i trpezarijski stolovi",
			"Fontane od čokolade", "USB kablovi", "Peškiri za ruke", "Sakoi i prsluci", "Posude za čuvanje kolača",
			"Tregeri", "WC šolje", "Bicikl", "Ćebad za kampovanje", "Sokovnici", "Električni uređaji za negu noktiju",
			"Rančevi", "Skije", "Pernice", "Krede za kosu", "Paste za kosu", "Setovi kuhinje za igru",
			"Vreće za spavanje", "Rumenila", "Štitnici za ekran", "Elastične trake za vežbanje", "Baštenski traktori",
			"Bilijarski stolovi", "Čiviluci za kapute", "Komode", "Kaputi i jakne", "Sapuni za brijanje", "Klizaljke",
			"Užad za penjanje", "Šetalice za bebe", "Knjige od platna za bebe", "Držači četkica za zube", "Pikado",
			"Losioni za samopotamnjivanje", "Oprema za nosače bicikla", "Dečje nalepnice", "Maske za kosu",
			"Jastučići za dojenje", "Sobni bicikli", "Roštilji za raklet", "Robot usisivači",
			"Električne mašine za gnječenje hrane", "Prenosni zvučnici", "BodyBalms", "Mašine za šivenje",
			"PublicAddressPaSystems", "Fenjeri za kampovanje", "Proizvodi za negu ušiju za kućne ljubimce",
			"Ekološki senzori za pametne domove", "Kape i šeširi", "Peškiri za bebe", "Zidne police u kupatilu",
			"Tastature", "Pokrivači za dečja kolica", "Četke i držači četki za toalete", "Dečji projektori za crtanje",
			"Putne torbe valjkastog oblika", "BB i CC kreme za lice", "Mikrotalasne pećnice", "Odbojkaške lopte",
			"Suknje", "Trenažeri za veslanje", "Dečje igračke - kompleti figurica", "Dezodoransi za stopala",
			"Električni uređaji za seckanje hrane", "Viseće igračke za bebe", "Lekovi za oči", "Gelovi za brijanje",
			"Slušalice i slušalice sa mikrofonom", "Fudbalske lopte", "Majice i potkošulje", "Kredenci za dnevnu sobu",
			"Projektori podataka", "Otvarači za flaše", "Penušave kupke", "Garniture nameštaja za kuhinje i trpezarije",
			"Trimeri za predeo bikinija", "Četke za čišćenje noktiju", "Fenovi za kosu",
			"Držači za šolju na kolicima za bebe", "Oprema za korpe za kola", "Mašine za mlevenje", "Lakovi za nokte",
			"Kolica za bebe", "Posude za nošenje hrane", "Tanjiri za fondi", "Čašice za žestoka pića",
			"Mašine za pranje sudova", "Vreće za skladištenje odeće", "Mašine za sušenje veša", "Oprema za masažu",
			"Epilacija", "Kutije za hleb", "Sofe", "Puderi za lice", "Balzami za brijanje",
			"Pernate loptice za badminton", "Barske stolice", "Audio kablovi", "Pribor za toalete",
			"Kompleti za serviranje sira", "Povijanje beba", "Dečji setovi za graviranje", "Balzami za kosu",
			"Sigurnosne kamere", "Štapovi za skijanje", "Ogledala za šminkanje", "Serumi za lice", "Prtljag",
			"Znojnice za ruke i narukvice", "Tegle", "Setovi opreme za fitnes i jogu", "Peškiri za kupatilo",
			"Sunđeri i prekrivači za pultove za presvlačenje", "Soundbar zvučnici", "Rezači za kreone",
			"Parne stanice za peglu", "Potrošni materijali i dodatna oprema za usisivače", "Zvučnici",
			"Dodatna oprema za aparate za brijanje", "Disk-tegovi", "Sanke", "Kućni audio sistemi",
			"Samobalansirajući skejtbordi", "Loptice za stoni tenis",
			"Klima uređaji koji se postavljaju na prozor ili kroz zid", "Početni kompleti za mobilne telefone",
			"Pametne utičnice", "Suva hrana za pse", "Japanke i papuče", "Sredstva za uklanjanje zanoktica",
			"Bezbednosne ograde za bebe", "Kompleti pečata za decu", "Dukseri sa kapuljačom i bez kapuljače",
			"Mreže za košarkaški obruč", "Ormari i garderoberi za spavaću sobu",
			"Prateća oprema za automobilske krovne nosače", "Kablovi za mobilne telefone",
			"Torbe za dasku za snoubording", "Uređaji za sušenje noktiju", "Peškiri za kosu", "Držači za toalet papir",
			"Monitori za računar", "Poklon setovi mirisa", "Sportski štitnici za usta/zube", "Šamponi za kosu",
			"Pomoćna oprema za plivanje", "Ogrlice za pse i mačke", "Pejzažna rasveta", "Maske pred manikir",
			"Kuhinjske vage", "Sunđerčići za šminku", "Komode i ormarići za dnevnu sobu", "Kuvala za vodu",
			"Skladišne police na vratima", "Grejači nožnih prstiju i stopala", "Lepkovi i lepljive trake za očne kapke",
			"Ogrlice", "Dečje table i sunđeri za suvo brisanje", "Rukavice za boks", "Sterilizatori za flašice",
			"Gel lakovi za nokte", "Maramice", "Prvi otisak", "Maskare za trepavice", "Stalci za audio-vizuelnu opremu",
			"Pribori za manikir/pedikir", "Žileti", "Kompleti tiganja i šerpi", "Reketi za stoni tenis",
			"Tende i paviljoni za kampovanje", "Džakovi i fokuseri za boks", "Sunđeri i četke za kupanje",
			"Neonske sijalice", "Dekorativni jastuci raznih oblika i veličina", "Dečji jastučići za mastilo",
			"Daske za snoubording", "Zamenske glave za električne četkice za zube", "Oprema za bicikle",
			"Loptice za tenis", "Kreveti", "Ulja za lice", "Preparati za sprečavanje opadanja kose", "Police za cipele",
			"Tečnosti za pranje i čišćenje lica", "LED sijalice", "Prahovi za kosu",
			"Dečji setovi za pravljenje nakita", "Posude za hranu za bebe", "Kutije za skladištenje",
			"Torbe za šivaće mašine", "Rerne", "Kašike", "Tende za kolica za bebe", "Produžni kablovi",
			"Ulja za masažu", "Kreme za zaštitu od sunca", "Vlažne maramice za kućne ljubimce", "Stolnjaci",
			"Suplementi minerala", "Pene za kupanje", "Dečji ukrasi za kosu", "Stolovi za menjanje pelena", "Girije",
			"Izbeljivanje zuba", "Kaiševi", "Salvete", "Prostirke za jogu", "Obuća za timske sportove", "Ekspander",
			"Zamenljivi delovi za krevete", "Oprema za penjanje na igralištu", "Usisivači", "Posude za kuvanje ribe",
			"Mleka za tuširanje", "Dečji kompleti za umetnost i rukotvorine", "Košarkaške lopte", "Pene za kosu",
			"Ormarići za kupatilo", "Organizatori za šminku", "Mašine za pranje veša",
			"Delovi i dodatna oprema za stolove za stoni tenis", "Tosteri za sendviče", "Bodi mist za kosu i telo",
			"Losioni za telo", "Vreće za sedenje", "Peškiri za lice", "Duvalice za lišće", "Farbe za obrve/trepavice",
			"Novčanici, futrole za kartice i držači putnih dokumenata", "Donji veš za celo telo",
			"Štitnici za atletska kolena", "Senke za obrve", "Prostirke za vežbu i igru za bebe",
			"Mašine za pranje i sušenje veša", "Epilatori", "Sapuni za pranje i čišćenje lica",
			"Trimeri/mašinice za kosu", "Daske za uzglavlje i podnožje kreveta", "Zaštitne maske za mobilne telefone",
			"Čitači kartica", "Serumi za nokte", "Prostirke za toalet", "Pomoćni stočići", "Šorcevi",
			"Televizijske antene", "Pletena odeća", "Postolja za bebi kadice", "Torbe za teniske rekete",
			"Delovi za štapove za skijanje, treking i hodanje", "Kablovi za startovanje automobila", "Selfi štapovi",
			"Osveživači vazduha", "Šminka za isticanje kontura", "Zaštita od šampona",
			"Dečje knjige o umetnosti i rukotvorinama", "Police za audio-vizuelnu opremu",
			"Termometri za vodu za kupanje", "Šumeće kugle za kupanje", "Minerali i soli za kupanje",
			"Oprema za postavljanje automobilskih krovnih nosača", "Puderi za obrve", "Tonici za lice", "Mopovi",
			"Prenosivi krevetac", "Pametni satovi", "Dečji kreveti", "Motorne testere", "Pegle", "Sportski tajmeri",
			"Rezači za picu", "Kreme za negu kože posle brijanja", "Termo-šolje", "Parfemi", "Aparati za sečenje hrane",
			"Sprejevi za lice", "Sportski kajaci", "Čistači na paru", "Vitamini i multivitamini",
			"Čamci na naduvavanje", "Kuhinjski aspiratori", "Oralni tuševi", "Ostali fitnes rekviziti", "Kišobrani",
			"Cookers", "Setovi posteljine", "Setovi za igranje", "Posuđe za kampovanje", "Društvene igre",
			"Fudbalski štitnici za cevanice", "Dugi i kratki donji delovi pidžama", "Preparati za jačanje noktiju",
			"Kreme posle sunčanja", "Bušilice", "Vikleri za kosu", "Peškiri za goste", "Kućne vage",
			"Električni skuteri", "Tegovi za vežbanje", "Viljuške", "Procesori za kuvanje hrane", "Vešalice za odeću",
			"Kuhinjske slavine", "Adapteri za WC šolju", "Prekrivači za krevet", "Narukvice za gležanj", "Akumulatori",
			"Kupaći kostimi", "Višenamenska sredstva za čišćenje", "Šamponi za suvo pranje kose", "Oprema za kroket",
			"Četke za kosu i češljevi", "Dodaci za sprave", "Skladišni ormarići za kuhinju", "Futrole za tablete",
			"Aparati za kokice", "Prekrivači za sedišta u dečjim kolicima", "Lutke",
			"Dodatna oprema za fudbalske golove", "Naočare za sunce", "Dečje police", "Roleri",
			"Uski dugački stolnjaci", "Torbe za bebi flašice", "Ugaone brusilice", "Dečja sedišta za bicikl",
			"Ulja za zanoktice", "Suplementi aminokiselina", "Aparati za piće", "Stolice za restorane i trpezarije",
			"Sportske mreže", "Koncentrovani preparati za kosu", "Šatori i tuneli za igru", "Kreme za telo", "Kafemati",
			"FM predajnici", "WC daske", "Postolja za televizore i druge uređaje za zabavu", "Kombinovani frižideri",
			"Predajnici za pametne domove", "Oprema za provodne cevi", "Četkice za senku", "Kape za tuširanje",
			"Hemijske olovke sa gelom", "Gelovi za obrve", "Štitnici ćoškova zbog bebe", "Trake za depilaciju",
			"Biciklističke brave za zaključavanje", "Kutije za četkice za zube", "Oprema za sportske satove",
			"Proizvodi za negu očiju za kućne ljubimce", "Separatori nožnih prstiju", "Mleka za telo",
			"Noćni ormarići i stočići", "Pištaljke za sudije", "Šipke za zgibove", "Vozila-igračke",
			"Dodatna oprema za masažere", "Stoni podmetači", "Reketi za tenis", "AirPurifierAccessories",
			"Spirografi za decu", "Dušeci na naduvavanje", "Dečje ograde za krevete",
			"Četke i češljevi za kućne ljubimce", "Lavaboi", "Piling za lice", "Albumi sa nalepnicama", "Mikseri",
			"Štitnici za prste za bebe", "Ručne torbe i torbe preko ramena", "Flašice za bebe", "Sofe za decu",
			"Brijači za telo", "Sokne", "Dečji stolovi za piknik", "Okviri za krevet", "Vrteške za krevetac", "Tableti",
			"Automobilske gume", "Prostirke za kupatilo", "Nosiljke za bebe", "Naočare za zimske sportove",
			"VacuumSealerAccessories", "Kreveci za bebe", "Gelovi za tuširanje", "Flaše za piće",
			"ElectricCookiePresses", "Modno dizajnerski setovi za decu", "Aparati za pravljenje kaše za bebe",
			"Dečji pribor za kuvanje", "Šipke za tegove", "Poslužavnici", "Oprema za kupatila", "Ženski brijači",
			"Igračke za simulaciju vožnje", "Lonci za kuvanje na dva nivoa", "Električne ubodne testere",
			"Oprema za pribor za oblikovanje kose", "Činije za ručavanje", "Proizvodi za kontrolu težine",
			"Papiri i posude za pečenje", "Aparati za pravljenje hleba", "Točkovi za kolica za bebe",
			"Kreme za oblikovanje kose", "Frižideri", "Kutije i tegle za keks", "Ručni šrafcigeri",
			"Radio prijemnici za kola", "Rekreacione i dvorišne trambuline", "Kutije za odlaganje igračaka",
			"Origami setovi za decu", "Kombinezoni", "Edukativne igračke", "Olovke za usne", "Torbe za kupovinu",
			"Veb kamere", "Automobilske kamere za snimanje vožnje", "Pribor za dojenje", "Paste za zube",
			"Oprema za bebi alarme", "Delovi i oprema za aspiratore", "Sportske pantalone", "Noćna svetla za bebe",
			"Stolovi za stoni tenis", "Elementi za odlaganje u kupatilu", "Tronošci", "Višenamenski lonci",
			"Vodootporne torbice", "Miševi", "Reketi za badminton", "Ležaljke za ljuljanje bebe", "Vijače",
			"Transformeri (igračke)", "Jastučnice", "Električne četkice za zube", "Torbe za nošenje kućnih ljubimaca",
			"Daljinski upravljači", "Manikirske makaze", "Prečke i kuke za peškire u kupatilu",
			"Dozatori za mleko u prahu", "Prstenje", "Table za pikado", "Adapteri za utikače",
			"Kompleti zaštitne sportske opreme", "Odstranjivači farbi za kosu", "Jednodelne pidžame",
			"Preparati za odmrsivanje kose", "Oprema koja se postavlja na krov automobila", "Kompleti za negu brade",
			"Četke za brijanje", "Suncobrani za dečja kolica", "Sedišta za kupanje beba", "Privremene boje za kosu",
			"Mlinovi za kafu", "Kuhinjski noževi", "Tiganji", "Kante za smeće", "Medicinske lopte", "Čizme",
			"Veštačke trepavice", "Dečji kompleti za livenje i slikanje", "Sportski kanui", "Kuhinjske kecelje",
			"Alchajmer kompleti posuđa", "Pribor za čišćenje jezika", "Kreme za ruke", "Grožđane masti", "CD plejeri",
			"Električni uređaji za zagrevanje flašica za bebe", "Stolice za decu", "Servisi",
			"Podloge za menjanje pelena", "Poslastice za pse i mačke", "Čaše za vino",
			"Turpije za oblikovanje i poliranje noktiju", "Prskalice vode", "Pantalone", "Rukavice za piling",
			"Oprema za zaštitne kacige", "Podloge za šminku", "Sigurnosni dodaci za kolica za bebe",
			"Aparati za kuvanje na pari", "Glave tuša", "Radkapne", "Štapni usisivači i električne metle",
			"Ormarići za skladištenje dečjih stvari", "Šerpe za mleko", "Kuhinjske fioke", "Trake za trčanje",
			"Držači posuda za pečenje", "Amovi za pse i mačke", "Dozatori vreća za otpad pasa i mačaka",
			"Grejači za vodu i bojleri", "Navlake za dečji dušek", "Kombinovani frižideri i zamrzivači",
			"Veštački nokti", "Noćni ormarići za decu", "Grickalice za nokte", "Ramovi za dušek",
			"Dozatori za suvu hranu", "Rukavice za teretanu", "Stolovi za aktivnost bebe", "Multipraktici",
			"Markeri za Airbrush slikanje", "Kinetički pesak", "Štapovi za rekreaciju", "Masažeri", "Četkice za zube",
			"Baze za usne", "Stikeri za nokte", "Vlažne maramice za pranje i čišćenje lica",
			"Užad, kablovi i lanci za šlepovanje", "Držači papirnih ubrusa", "Oprema za kupanje beba",
			"Brijači za muškarce", "Torbe za skije", "Korektori za farbu za kosu", "Osveživači vazduha u kolima",
			"CarDoorsWindowsComponents", "Sredstva za negu brade i brkova", "Posude za pesak za pse i mačke",
			"Pojasevi za trudnice", "Knjige", "Kutije za čaj", "Telefoni", "Berberske četke", "Maskare za obrve",
			"Mlečne formule za bebe", "Pištolji za vruć vazduh", "Sprejevi za kosu", "Gelovi za kosu", "Dušeci za bebe",
			"Dezodoransi");

	static Random random = new Random();

	public static List<String> getColumns(String productType) {
		List<String> list = new ArrayList<>();
		list.addAll(List.of("Naziv", "EAN", "Slika", "Opis", "Brend"));
		if (random.nextBoolean()) {
			list.add("Visina");
		}
		if (random.nextBoolean()) {
			list.add("Tezina");
		}
		if (random.nextBoolean()) {
			list.add("Sirina");
		}
		if (random.nextBoolean()) {
			list.add("Boja");
		}
		if (random.nextBoolean()) {
			list.add("Velicina");
		}
		if (random.nextBoolean()) {
			list.add("Dijagonala");
		}
		if (random.nextBoolean()) {
			list.add("Materijal");
		}
		return list;
	}

}
